# This is a basic workflow to help you get started with Actions

name: Deploy React-with-yarn to Surge

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Install NodeJS
    - name: Install NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    # will run `yarn install` command
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install 
     # will run `yarn build` command
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build
     # Install surge
    - name: Install Surge
      run: npm install --global surge 
    
    #Deploy Surge
    - name: Deploy React-with-yarn to Surge
      run: surge ./build react-tasks-for-assignment3-by-Arshia.surge.sh --token ${{secrets.SECRET_SURGE}}
